INSERT INTO ticket (titre, descriptif, statut, priority, categorie, assignation, datetime, Id_utilisateur )
VALUES
    ('Problème de performance', 'L\'application est lente à répondre', 'En cours', 'Moyenne', 'Technique', 'Alice Johnson', '2023-12-24 12:00:00',1),
    ('Demande de fonctionnalité', 'Ajouter une nouvelle fonctionnalité au système', 'Ouvert', 'Basse', 'Développement', 'Ethan Brown', '2023-12-25 15:30:00',3),
    ('Problème d\'impression', 'Les documents ne s\'impriment pas correctement', 'En attente', 'Haute', 'Support', 'Emily Davis', '2023-12-26 11:45:00',2),
    ('Question sur la facturation', 'Besoin de clarification sur une facture', 'Nouveau', 'Basse', 'Finance', 'Sophia Wilson', '2023-12-27 08:20:00',2),
    ('Demande de congé', 'Demander des jours de congé', 'En attente', 'Urgente', 'Ressources humaines', 'Matthew Miller', '2023-12-28 13:10:00',3),
    ('Problème d\'accès au fichier', 'Impossible d\'accéder à un fichier partagé', 'En cours', 'Moyenne', 'Technique', 'Olivia White', '2023-12-29 09:50:00',3),
    ('Réclamation sur un produit', 'Problème avec un produit livré', 'Ouvert', 'Haute', 'Service client', 'Daniel Lee', '2023-12-30 14:15:00',3),
    ('Problème de connexion', 'Je ne peux pas me connecter à mon compte', 'Ouvert', 'Haute', 'Technique', 'John Doe', '2023-12-21 10:30:00',1),
    ('Problème d\'affichage', 'L\'interface utilisateur ne s\'affiche pas correctement', 'En cours', 'Moyenne', 'Design', 'Jane Smith', '2023-12-22 14:45:00',2),
    ('Erreur dans le traitement des paiements', 'Les paiements en ligne ne fonctionnent pas', 'Nouveau', 'Urgente', 'Finance', 'Bob Johnson', '2023-12-23 09:15:00',1),
    ('Problème de connexion 1', 'Je ne peux pas me connecter à mon compte', 'Ouvert', 'Haute', 'Technique', 'John Doe', '2023-12-21 10:30:00',3),
    ('Problème d\'affichage 1', 'L\'interface utilisateur ne s\'affiche pas correctement', 'En cours', 'Moyenne', 'Design', 'Jane Smith', '2023-12-22 14:45:00',2),
    ('Erreur dans le traitement des paiements 1', 'Les paiements en ligne ne fonctionnent pas', 'Nouveau', 'Urgente', 'Finance', 'Bob Johnson', '2023-12-23 09:15:00',3),
    ('Problème de performance 1', 'L\'application est lente à répondre', 'En cours', 'Moyenne', 'Technique', 'Alice Johnson', '2023-12-24 12:00:00',1),
    ('Demande de fonctionnalité 1', 'Ajouter une nouvelle fonctionnalité au système', 'Ouvert', 'Basse', 'Développement', 'Ethan Brown', '2023-12-25 15:30:00',3),
    ('Problème d\'impression 1', 'Les documents ne s\'impriment pas correctement', 'En attente', 'Haute', 'Support', 'Emily Davis', '2023-12-26 11:45:00',3),
    ('Question sur la facturation 1', 'Besoin de clarification sur une facture', 'Nouveau', 'Basse', 'Finance', 'Sophia Wilson', '2023-12-27 08:20:00',1),
    ('Demande de congé 1', 'Demander des jours de congé', 'En attente', 'Urgente', 'Ressources humaines', 'Matthew Miller', '2023-12-28 13:10:00',2),
    ('Problème d\'accès au fichier 1', 'Impossible d\'accéder à un fichier partagé', 'En cours', 'Moyenne', 'Technique', 'Olivia White', '2023-12-29 09:50:00',3),
    ('Réclamation sur un produit 1', 'Problème avec un produit livré', 'Ouvert', 'Haute', 'Service client', 'Daniel Lee', '2023-12-30 14:15:00',1),
    ('Problème de connexion 2', 'Je ne peux pas me connecter à mon compte', 'Ouvert', 'Haute', 'Technique', 'John Doe', '2023-12-21 10:30:00',3),
    ('Problème d\'affichage 2', 'L\'interface utilisateur ne s\'affiche pas correctement', 'En cours', 'Moyenne', 'Design', 'Jane Smith', '2023-12-22 14:45:00',3),
    ('Erreur dans le traitement des paiements 2', 'Les paiements en ligne ne fonctionnent pas', 'Nouveau', 'Urgente', 'Finance', 'Bob Johnson', '2023-12-23 09:15:00',1),
    ('Problème de performance 2', 'L\'application est lente à répondre', 'En cours', 'Moyenne', 'Technique', 'Alice Johnson', '2023-12-24 12:00:00',2),
    ('Demande de fonctionnalité 2', 'Ajouter une nouvelle fonctionnalité au système', 'Ouvert', 'Basse', 'Développement', 'Ethan Brown', '2023-12-25 15:30:00',3),
    ('Problème d\'impression 2', 'Les documents ne s\'impriment pas correctement', 'En attente', 'Haute', 'Support', 'Emily Davis', '2023-12-26 11:45:00',1),
    ('Question sur la facturation 2', 'Besoin de clarification sur une facture', 'Nouveau', 'Basse', 'Finance', 'Sophia Wilson', '2023-12-27 08:20:00',4),
    ('Demande de congé 2', 'Demander des jours de congé', 'En attente', 'Urgente', 'Ressources humaines', 'Matthew Miller', '2023-12-28 13:10:00',4),
    ('Problème d\'accès au fichier 2', 'Impossible d\'accéder à un fichier partagé', 'En cours', 'Moyenne', 'Technique', 'Olivia White', '2023-12-29 09:50:00',4),
    ('Réclamation sur un produit 2', 'Problème avec un produit livré', 'Ouvert', 'Haute', 'Service client', 'Daniel Lee', '2023-12-30 14:15:00',3);

